"""add telegram_chat_id to user

Revision ID: 2865103c0ba2
Revises: 
Create Date: 2026-02-19 01:11:02.984936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2865103c0ba2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telegram_chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telegram_chat_id',
               existing_type=sa.String(length=64),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
